[project]
name = "gloin_project"
version = "0.1.0"

[dependencies]
http_client = { version = "1.0.0", url = "github.com/user/http_client" }
crypto = { version = "2.1.3", url = "github.com/user/crypto_lib" }
